# **Import Libraries**

In [ ]:
import numpy
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.2'

#**Import Dataset**

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


# **Encoding Categorical Data**

Label Encodig the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder='passthrough')
x = numpy.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Split the dataset into Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# **Building the ANN**

Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

Adding the second layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# **Training the ANN**

Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the ANN on the Training set

In [19]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6575 - accuracy: 0.6349
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7958
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4418 - accuracy: 0.7979
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.8054
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4183 - accuracy: 0.8123
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4079 - accuracy: 0.8171
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3976 - accuracy: 0.8235
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3881 - accuracy: 0.8303
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3799 - accura

Predict Result

* Geograpy: France
* Credit Score: 600
* Gender: Male
* Age: 40 years old
* Tenure: 3 years
* Balance: $ 60000
* Number of Products: 2
* Does this customer have a credit card: yes
* Is this customer an Active Member: yes
* Estimated Salary: 50000
* So, should we say goodbye to that customer?




In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 5000]])) > 0.5)

[[False]]


# **Predicting the Test set results**

In [28]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(numpy.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# **Making the Confusion Matrix** 

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1519   76]
 [ 186  219]]


0.869